name       : perl-term-size-any
version    : 0.002
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Term-Size-Any-0.002.tar.gz : 64fa5fdb1ae3a823134aaa95aec75354bc17bdd9ca12ba0a7ae34a7e51b3ded2
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://metacpan.org/release/Term-Size-Any
summary    : Term::Size::Any - Retrieve terminal size
description: |
    Term::Size::Any - Retrieve terminal size
builddeps  :
    - perl-devel-hide
    - perl-term-size-perl
    - perl-test-pod
    - perl-test-pod-coverage
rundeps    :
    - perl-term-size-perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
